# Numpy Exercise Solution  <img src = "numpy1.png">
###### Authored by Nagendra yadav

#### 1. Create a numpy array with the number of elements equals your age. The value of array elements is a random number between 10 to your age 

In [2]:
import numpy as np
import array
np.random.randint(10,22,size=22)


array([10, 18, 12, 12, 21, 10, 11, 21, 13, 14, 16, 20, 10, 19, 11, 17, 12,
       21, 21, 15, 18, 19])

#### 2. Create a numpy array between 1 to 50 with the span(space) of 2 and print the length of the array

In [5]:
x=np.arange(1,50,step=2)
print(x)
print(len(x))



[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]
25


#### 3. Create an equally spaced numpy array with 27 elements between 4 and 7 

In [8]:
np.linspace(4,7,num=27,dtype=int)


array([4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6,
       6, 6, 6, 6, 7])

#### 4. Create a matrix of size (5 x 4) with random numbers and round off the each elements by only 2 fractional points.

In [15]:
# Solution
x=np.random.random((5,4))

print(np.round(x,2))



[[0.16 0.59 0.55 0.01]
 [0.58 0.69 0.29 0.52]
 [0.82 0.39 0.16 0.83]
 [0.05 0.29 0.93 0.47]
 [0.65 0.61 0.6  0.2 ]]


#### 5. Create a matrix of size (5x5) with random integers between 5 to 15

In [10]:
# Solution
np.random.randint(5,15,(5,5))


array([[ 7,  5, 10, 12, 14],
       [13, 14,  9,  9, 12],
       [ 5, 12,  9, 10,  8],
       [13, 14, 14,  6, 13],
       [ 9,  7, 13, 13,  8]])

#### 6. Create the one dimensional array of zeros of random length below 20 with the data type int32

In [3]:
# Solution
np.zeros(np.random.randint(1,20),dtype="float64")



array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.])

#### 7. Create a two dimensional array of ones of random row and column lengths with the data type of float32 

In [8]:
# Solution
np.ones(np.random.randint(1,20),dtype="int32")



#### 8. Create a matrix exactly as same as shown below and print its shape, type and dtype
<img src = "np_mat1.png">

In [35]:
# Solution
var=np.array([9,25,50,34,45,3,34,34,65,2,5,7,3,76,3,7,8,6,54,6,23,12,8,5,8])
z=var.reshape(5,5)
print(z)
a,b=z.shape
print("the diminsion",z.ndim) 
print("the shape of value",z.shape)
print("the dtype is ",z.dtype)

[[ 9 25 50 34 45]
 [ 3 34 34 65  2]
 [ 5  7  3 76  3]
 [ 7  8  6 54  6]
 [23 12  8  5  8]]
the diminsion 2
the shape of value (5, 5)
the dtype is  int32


#### 9. Access the center pixel of the matrix defined in the question no 8 ( Don't enter the row and column index explicitely)

In [42]:
# Solution
print(z[a//2][b//2])



3


#### 10. Print the all the elements of 3rd row of the matrix

In [44]:
# Solution
print(z[2])


[ 5  7  3 76  3]


#### 11. Print the all the elements of 4th columns of the matrix

In [57]:
# Solution
print(z[:,3:4])



[[34]
 [65]
 [76]
 [54]
 [ 5]]


#### 12. Print the 4 corner pixels of the matrix

In [202]:
# Solution
print(z[0][0],z[0][4],z[4][0],z[4][4])

9 45 23 8


#### 13. Create three matrix m1,m2,m3 with the elements grouped in the figure below
<img src = "np_mat2.png">

In [90]:
# Solution
m1=z[0:2,2:4]
m3=z[2:5,2:5]
m2=z[3:5,0:2]
print(m1)
print(m2)
print(m3)

[[50 34]
 [34 65]]
[[ 7  8]
 [23 12]]
[[ 3 76  3]
 [ 6 54  6]
 [ 8  5  8]]


#### 14. Reshape all the three matrix segmented in the above task in to three  1-dimensional vector.

In [80]:
print(m1.reshape(1,4))
print(m3.reshape(1,9))
print(m2.reshape(1,4))

[[50 34 34 65]]
[[ 3 76  3  6 54  6  8  5  8]]
[[ 7  8 23 12]]


#### 15. Concatenate the matrix m1 and m2 in both vertical and horizontal direction

In [81]:
# Solution
print(np.concatenate([m1,m2],axis=1))
print(np.concatenate([m1,m2]))

[[50 34  7  8]
 [34 65 23 12]]
[[50 34]
 [34 65]
 [ 7  8]
 [23 12]]


#### 16. Add, Subtract, multiply, divide the matrixes m1 and m2

In [85]:
# Solution
add=m1+m2
print(add)
sub=m1-m2
print(sub)
mul=m1*m2
print(mul)
div=m1/m2
print(div)


[[57 42]
 [57 77]]
[[43 26]
 [11 53]]
[[350 272]
 [782 780]]
[[7.14285714 4.25      ]
 [1.47826087 5.41666667]]


#### 17. Add the m1 with m3 by removing the first row and last column of m3

In [106]:
# Solution
m5=m3[1:3,0:2]
print(m1+m5)


[[56 88]
 [42 70]]


#### 18. Form the matrix m4 by concatenating (as a new row) the vector [me1, me2] with the matrix m1, where me1 and me2 are the mean values of each column on m1.

In [132]:
# Solution
me1=np.mean(m1[:,0:1],dtype=int)
me2=np.mean(m1[:,1:2],dtype=int)
vect=np.array([me1,me2])
m4=np.concatenate([m1,[vect]],axis=0)
print(m4)



[[50 34]
 [34 65]
 [42 49]]


#### 19. Perform the matrix multiplication between m3 and m4

In [135]:
# Solution
np.dot(m3,m4)


array([[2860, 5189],
       [2388, 4008],
       [ 906,  989]])

#### 20. Compute the maximum and minimum value of mean, variance, standard deviation for each row of matrix created in question number 8.

In [157]:
# Solution
r1=np.mean(z[0:1,0:5])
r2=np.mean(z[1:2,0:5])
r3=np.mean(z[2:3,0:5])
r4=np.mean(z[3:4,0:5])
r5=np.mean(z[4:5,0:5])
print("The maximum mean is",max(r1,r2,r3,r4,r5))
print("The maximum mean is",min(r1,r2,r3,r4,r5))
s1=np.std(z[0:1,0:5])
s2=np.std(z[1:2,0:5])
s3=np.std(z[2:3,0:5])
s4=np.std(z[3:4,0:5])
s5=np.std(z[4:5,0:5])

print("The maximum standard deviation is",max(s1,s2,s3,s4,s5))
print("The minimum standard deviation is",min(s1,s2,s3,s4,s5))
v1=np.var(z[0:1,0:5])
v2=np.var(z[1:2,0:5])
v3=np.var(z[2:3,0:5])
v4=np.var(z[3:4,0:5])
v5=np.var(z[4:5,0:5])
max(v1,v2,v3,v4,v5)
print("The maximum variance is",max(v1,v2,v3,v4,v5))
print("The minimum variance is",min(v1,v2,v3,v4,v5))


The maximum mean is 32.6
The maximum mean is 11.2
The maximum standard deviation is 28.63843571147
The minimum standard deviation is 6.305553108173779
The maximum variance is 820.1600000000001
The minimum variance is 39.760000000000005


# 21. Compute the average and strike rate for each player and sort it decending way (seperately for avg and strike rate)

<img src = 'crick1.png'>

In [200]:
# Solution 
runs=np.array([54,60,10,65,102,2,78,32,3,110,1,92,56,6,12,42,12,8,22,11])
balls=np.array([50,42,22,78,95,8,65,43,9,100,7,101,27,3,11,31,24,20,36,27])
MSD =sum(runs[:4])*100/sum(balls[:4])
avg1=sum(runs[:4])/4
Kohli= sum(runs[4:8])*100/sum(balls[4:8])
avg2=sum(runs[4:8])/4
Rohit=sum(runs[8:12])*100/sum(balls[8:12])
avg3=sum(runs[8:12])/4
Rahul=sum(runs[12:16])*100/sum(balls[12:16])
avg4=sum(runs[12:16])/4
Dhawan= sum(runs[16:20])*100/sum(balls[16:20])
avg5=sum(runs[16:20])/4
strike_rate=np.array([MSD,Kohli,Rohit,Rahul,Dhawan])
Average=np.array([avg1,avg2,avg3,avg4,avg5])
a=np.sort(strike_rate)
b=np.sort(Average)
print(a[::-1])
print(b[::-1])



[161.11111111 101.42180095  98.4375      94.93087558  49.53271028]
[53.5  51.5  47.25 29.   13.25]


#### 22. The students mark was recorded in a numpy array: marks = np.array([65,84,47,56,89,98,48,77,80,39]).  Cutoff for pass is 50 marks. Write the logic to print the number of students passed and failed. 

In [179]:
marks = np.array([65,84,47,56,89,98,48,77,80,39])
count=0
count2=0
for i in marks:
    if i>50:
        count+=1
    else:
        count2+=1
print("Number Of Students Passed =",count)
print("Number Of Students Failed =",count2)

Number Of Students Passed = 7
Number Of Students Failed = 3


#### 23. The class incharge decided to give a mercy mark of 5 for those who scored between 45 and 49. Also the bonus of 5 marks awarded to the students who scored more than 80. Print all the student marks and compute the increase in the pass percentage of class. Any score more than 100 must be recorded as only 100.

In [189]:
intial_pass=count*100/10
y=len(marks)
count3=0
for i in range(y):
    if(marks[i]>80):
        marks[i]=marks[i]+5
    elif(marks[i]>45)and(marks[i]<49):
        marks[i]+=5
    elif(marks[i]>100):
        marks[i]=100
    if(marks[i]>50):
        count3+=1
        
final_pass=count3*100/10            
    
print(marks)
print("Increase in Pass Percentage",(final_pass-intial_pass))


[ 65 104  52  56 109 118  53  77  80  39]
Increase in Pass Percentage 20.0


#### 24. Print the time taken for performing the following operation using list and numpy array
####       (x(i)^2 +8) / y(i),   where x and y are real integers from 1 to 60000

In [192]:
import time
starttime=time.time()
for i in range(1,60000):
    c=i**2+8/i
endtime=time.time()
print(endtime-starttime)

0.15810298919677734


#### 25. Create a Github account and upload your solution with the short write-up on Numpy

# Solution
NumPy is a Python library used for working with arrays.
It also has functions for working in domain of linear algebra, fourier transform, and matrices.
NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.
NumPy stands for Numerical Python.
NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.
Why we use Numpy over List?
The reason is NumPy is faster than lists. Also it is optimized to work with latest CPU architectures



